name: saf
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - opencv
  - tensorboardx
  - scipy
  - pycocotools
  - cython
  - matplotlib
  - pytorch==0.4.1
  - torchvision[version='>=0.2.0']
  - numpy[version='>=1.16']
  - scikit-learn
  - cuda90
  - pyyaml==3.12
  - packaging
